[build]
  command = "ng build --configuration production"
  publish = "dist/desafio-incaas/browser"

[[redirects]]
  from = "/api/*"
  to = "https://api-publica.datajud.cnj.jus.br/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
