[build]
  command = "ng build --prod"
  publish = "dist/desafio-incaas"  # ajuste conforme seu outputPath

[[redirects]]
  from = "/api/*"
  to = "https://api-publica.datajud.cnj.jus.br/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
